export const GET_USERS_LIST = 'GET_USERS_LIST';
export const RECIEVE_USERS_LIST = 'RECIEVE_USERS_LIST';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const RECIEVE_USER_DETAILS = 'RECIEVE_USER_DETAILS';